/**
 * @file web_ui.c
 * @brief 内嵌 Web 可视化管理 UI 与 REST API 实现
 * 
 * 💡 设计亮点：
 * 1. 零外部前端框架依赖：纯 HTML5 + CSS3 (Glassmorphism 毛玻璃风格) + Vanilla JS。
 * 2. 嵌入式二进制发布：静态 HTML 直接嵌入 C 语言源码字符串中，编译后无需部署任何前端静态资源。
 * 3. 实时交互：支持可视化的规则增删改查、开关切换、延迟滑块调节、实时应用与指标监控。
 */

#include "web_ui.h"
#include "rule_engine.h"
#include "logger.h"

/* 内嵌 HTML/CSS/JS 静态单页应用 (SPA) */
static const char *WEB_UI_HTML = 
"<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"  <title>Chaos-Proxy 控制台</title>\n"
"  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
"  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
"  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\n"
"  <style>\n"
"    :root {\n"
"      --bg-dark: #0f172a;\n"
"      --panel-bg: rgba(30, 41, 59, 0.7);\n"
"      --panel-border: rgba(255, 255, 255, 0.1);\n"
"      --accent-purple: #8b5cf6;\n"
"      --accent-cyan: #06b6d4;\n"
"      --accent-pink: #ec4899;\n"
"      --text-main: #f8fafc;\n"
"      --text-muted: #94a3b8;\n"
"      --success: #10b981;\n"
"      --danger: #ef4444;\n"
"    }\n"
"    * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Inter', system-ui, sans-serif; }\n"
"    body {\n"
"      background: var(--bg-dark);\n"
"      background-image: \n"
"        radial-gradient(at 0% 0%, rgba(139, 92, 246, 0.15) 0px, transparent 50%),\n"
"        radial-gradient(at 100% 100%, rgba(6, 182, 212, 0.15) 0px, transparent 50%);\n"
"      color: var(--text-main);\n"
"      min-height: 100vh;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"    }\n"
"    header {\n"
"      background: rgba(15, 23, 42, 0.8);\n"
"      backdrop-filter: blur(12px);\n"
"      border-bottom: 1px solid var(--panel-border);\n"
"      padding: 1rem 2rem;\n"
"      display: flex;\n"
"      justify-content: space-between;\n"
"      align-items: center;\n"
"      position: sticky;\n"
"      top: 0;\n"
"      z-index: 100;\n"
"    }\n"
"    .logo-box { display: flex; align-items: center; gap: 0.75rem; }\n"
"    .logo-badge { background: linear-gradient(135deg, var(--accent-purple), var(--accent-pink)); width: 36px; height: 36px; borderRadius: 8px; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 1.2rem; box-shadow: 0 0 15px rgba(236,72,153,0.3); }\n"
"    .logo-title { font-size: 1.25rem; font-weight: 700; background: linear-gradient(to right, #fff, var(--text-muted)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }\n"
"    .header-actions { display: flex; gap: 1rem; align-items: center; }\n"
"    .btn {\n"
"      background: linear-gradient(135deg, var(--accent-purple), #6d28d9);\n"
"      color: #fff; border: none; padding: 0.6rem 1.2rem; border-radius: 8px; font-weight: 600;\n"
"      cursor: pointer; transition: all 0.2s; display: inline-flex; align-items: center; gap: 0.5rem;\n"
"      box-shadow: 0 4px 12px rgba(139, 92, 246, 0.3);\n"
"    }\n"
"    .btn:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(139, 92, 246, 0.5); }\n"
"    .btn-secondary { background: rgba(255,255,255,0.05); border: 1px solid var(--panel-border); box-shadow: none; }\n"
"    .btn-secondary:hover { background: rgba(255,255,255,0.1); border-color: rgba(255,255,255,0.2); transform: none; }\n"
"    \n"
"    .main-container { display: grid; grid-template-columns: 340px 1fr; gap: 1.5rem; padding: 1.5rem 2rem; flex: 1; }\n"
"    .panel {\n"
"      background: var(--panel-bg);\n"
"      backdrop-filter: blur(16px);\n"
"      border: 1px solid var(--panel-border);\n"
"      border-radius: 12px;\n"
"      padding: 1.25rem;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"    }\n"
"    .panel-title { font-size: 1rem; font-weight: 600; margin-bottom: 1rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em; display: flex; justify-content: space-between; align-items: center; }\n"
"    \n"
"    .rule-list { display: flex; flex-direction: column; gap: 0.75rem; overflow-y: auto; max-height: calc(100vh - 200px); }\n"
"    .rule-item {\n"
"      background: rgba(15, 23, 42, 0.6);\n"
"      border: 1px solid var(--panel-border);\n"
"      padding: 1rem; border-radius: 10px; cursor: pointer; transition: all 0.2s;\n"
"      display: flex; flex-direction: column; gap: 0.5rem;\n"
"    }\n"
"    .rule-item:hover, .rule-item.active {\n"
"      border-color: var(--accent-purple);\n"
"      background: rgba(139, 92, 246, 0.1);\n"
"    }\n"
"    .rule-header { display: flex; justify-content: space-between; align-items: center; }\n"
"    .rule-name { font-weight: 600; font-size: 0.95rem; }\n"
"    .badge { padding: 0.2rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }\n"
"    .badge-method { background: rgba(6, 182, 212, 0.2); color: var(--accent-cyan); }\n"
"    .rule-url { font-size: 0.85rem; color: var(--text-muted); font-family: monospace; word-break: break-all; }\n"
"    \n"
"    .switch { position: relative; display: inline-block; width: 40px; height: 22px; }\n"
"    .switch input { opacity: 0; width: 0; height: 0; }\n"
"    .slider { position: absolute; cursor: pointer; top: 0; left: 0; right: 0; bottom: 0; background-color: rgba(255,255,255,0.2); transition: .3s; border-radius: 22px; }\n"
"    .slider:before { position: absolute; content: \"\"; height: 16px; width: 16px; left: 3px; bottom: 3px; background-color: white; transition: .3s; border-radius: 50%; }\n"
"    input:checked + .slider { background-color: var(--success); }\n"
"    input:checked + .slider:before { transform: translateX(18px); }\n"
"    \n"
"    .editor-form { display: flex; flex-direction: column; gap: 1.25rem; }\n"
"    .form-group { display: flex; flex-direction: column; gap: 0.5rem; }\n"
"    .form-label { font-size: 0.85rem; font-weight: 600; color: var(--text-muted); }\n"
"    .form-input, .form-select { background: rgba(15, 23, 42, 0.8); border: 1px solid var(--panel-border); color: #fff; padding: 0.75rem 1rem; border-radius: 8px; font-size: 0.95rem; outline: none; transition: border-color 0.2s; }\n"
"    .form-input:focus, .form-select:focus { border-color: var(--accent-purple); }\n"
"    .range-box { display: flex; align-items: center; gap: 1rem; }\n"
"    .range-box input[type=range] { flex: 1; accent-color: var(--accent-purple); }\n"
"    .range-val { width: 80px; text-align: right; font-weight: 600; font-family: monospace; color: var(--accent-cyan); }\n"
"    \n"
"    .metrics-bar { display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 1.5rem; }\n"
"    .metric-card { background: rgba(15, 23, 42, 0.5); border: 1px solid var(--panel-border); padding: 1rem; border-radius: 10px; display: flex; flex-direction: column; gap: 0.25rem; }\n"
"    .metric-num { font-size: 1.5rem; font-weight: 700; color: #fff; }\n"
"    .metric-title { font-size: 0.8rem; color: var(--text-muted); }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <header>\n"
"    <div class=\"logo-box\">\n"
"      <div class=\"logo-badge\">⚡</div>\n"
"      <div class=\"logo-title\">Chaos-Proxy 可视化控制台</div>\n"
"    </div>\n"
"    <div class=\"header-actions\">\n"
"      <button class=\"btn btn-secondary\" onclick=\"fetchRules()\">🔄 刷新配置</button>\n"
"      <button class=\"btn\" onclick=\"saveRules()\">💾 保存并同步生效</button>\n"
"    </div>\n"
"  </header>\n"
"\n"
"  <div class=\"main-container\">\n"
"    <!-- 左侧规则列表面板 -->\n"
"    <div class=\"panel\">\n"
"      <div class=\"panel-title\">\n"
"        <span>规则列表</span>\n"
"        <button class=\"btn btn-secondary\" style=\"padding: 0.3rem 0.6rem; font-size: 0.8rem;\" onclick=\"addNewRule()\">+ 新增规则</button>\n"
"      </div>\n"
"      <div class=\"rule-list\" id=\"ruleList\"></div>\n"
"    </div>\n"
"\n"
"    <!-- 右侧故障配置编辑器 -->\n"
"    <div class=\"panel\">\n"
"      <div class=\"metrics-bar\">\n"
"        <div class=\"metric-card\"><div class=\"metric-num\" id=\"mTotal\">0</div><div class=\"metric-title\">总拦截请求数</div></div>\n"
"        <div class=\"metric-card\"><div class=\"metric-num\" style=\"color:var(--success)\" id=\"mForwarded\">0</div><div class=\"metric-title\">正常转发请求</div></div>\n"
"        <div class=\"metric-card\"><div class=\"metric-num\" style=\"color:var(--accent-pink)\" id=\"mInjected\">0</div><div class=\"metric-title\">故障注入总数</div></div>\n"
"        <div class=\"metric-card\"><div class=\"metric-num\" style=\"color:var(--accent-cyan)\" id=\"mDelay\">0</div><div class=\"metric-title\">延迟注入数</div></div>\n"
"      </div>\n"
"\n"
"      <div class=\"panel-title\">故障注入配置参数</div>\n"
"      <div class=\"editor-form\" id=\"editorForm\" style=\"display:none;\">\n"
"        <div class=\"form-group\">\n"
"          <label class=\"form-label\">规则名称</label>\n"
"          <input type=\"text\" class=\"form-input\" id=\"ruleName\" placeholder=\"输入规则名称描述...\">\n"
"        </div>\n"
"        <div style=\"display:flex; gap:1rem;\">\n"
"          <div class=\"form-group\" style=\"flex:1;\">\n"
"            <label class=\"form-label\">匹配 URL (支持子串匹配)</label>\n"
"            <input type=\"text\" class=\"form-input\" id=\"matchUrl\" placeholder=\"例如: /api/user/login\">\n"
"          </div>\n"
"          <div class=\"form-group\" style=\"width:150px;\">\n"
"            <label class=\"form-label\">HTTP 方法</label>\n"
"            <select class=\"form-select\" id=\"matchMethod\">\n"
"              <option value=\"\">任意 (ANY)</option>\n"
"              <option value=\"GET\">GET</option>\n"
"              <option value=\"POST\">POST</option>\n"
"              <option value=\"PUT\">PUT</option>\n"
"              <option value=\"DELETE\">DELETE</option>\n"
"            </select>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <hr style=\"border:none; border-top:1px solid var(--panel-border); margin:0.5rem 0;\">\n"
"\n"
"        <div class=\"form-group\">\n"
"          <label class=\"form-label\">响应延迟注入 (Latency Delay)</label>\n"
"          <div class=\"range-box\">\n"
"            <input type=\"range\" id=\"delaySlider\" min=\"0\" max=\"10000\" step=\"100\" value=\"0\" oninput=\"updateDelayVal(this.value)\">\n"
"            <div class=\"range-val\" id=\"delayVal\">0 ms</div>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div class=\"form-group\">\n"
"          <label class=\"form-label\">HTTP 状态码篡改 (Status Code Override)</label>\n"
"          <select class=\"form-select\" id=\"statusCode\">\n"
"            <option value=\"0\">不篡改 (保持原样)</option>\n"
"            <option value=\"500\">500 Internal Server Error</option>\n"
"            <option value=\"503\">503 Service Unavailable</option>\n"
"            <option value=\"429\">429 Too Many Requests</option>\n"
"            <option value=\"404\">404 Not Found</option>\n"
"          </select>\n"
"        </div>\n"
"\n"
"        <div style=\"display:flex; gap:1rem;\">\n"
"          <div class=\"form-group\" style=\"flex:1;\">\n"
"            <label class=\"form-label\">Body 待查找替换字符串 (find)</label>\n"
"            <input type=\"text\" class=\"form-input\" id=\"bodyFind\" placeholder='例如: \"code\":0'>\n"
"          </div>\n"
"          <div class=\"form-group\" style=\"flex:1;\">\n"
"            <label class=\"form-label\">Body 替换目标字符串 (replace)</label>\n"
"            <input type=\"text\" class=\"form-input\" id=\"bodyReplace\" placeholder='例如: \"code\":5'>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <div style=\"display:flex; justify-content:space-between; align-items:center; margin-top:1rem;\">\n"
"          <div>\n"
"            <span class=\"form-label\" style=\"margin-right:1rem;\">瞬间中断连接 (Close Connection)</span>\n"
"            <label class=\"switch\"><input type=\"checkbox\" id=\"closeDrop\"><span class=\"slider\"></span></label>\n"
"          </div>\n"
"          <button class=\"btn btn-secondary\" style=\"color:var(--danger); border-color:rgba(239,68,68,0.3);\" onclick=\"deleteCurrentRule()\">🗑 删除该规则</button>\n"
"        </div>\n"
"      </div>\n"
"      <div id=\"emptyState\" style=\"text-align:center; padding:4rem; color:var(--text-muted);\">👈 请选择左侧规则或点击新增规则开始配置</div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    let rulesData = [];\n"
"    let currentRuleIdx = -1;\n"
"\n"
"    async function fetchRules() {\n"
"      try {\n"
"        const res = await fetch('/api/rules');\n"
"        rulesData = await res.json();\n"
"        renderRuleList();\n"
"        fetchMetrics();\n"
"      } catch(e) { console.error(e); }\n"
"    }\n"
"\n"
"    async function fetchMetrics() {\n"
"      try {\n"
"        const res = await fetch('/api/metrics');\n"
"        const m = await res.json();\n"
"        document.getElementById('mTotal').innerText = m.total || 0;\n"
"        document.getElementById('mForwarded').innerText = m.forwarded || 0;\n"
"        document.getElementById('mInjected').innerText = m.injected || 0;\n"
"        document.getElementById('mDelay').innerText = m.delay || 0;\n"
"      } catch(e){}\n"
"    }\n"
"\n"
"    function renderRuleList() {\n"
"      const list = document.getElementById('ruleList');\n"
"      list.innerHTML = '';\n"
"      rulesData.forEach((r, idx) => {\n"
"        const item = document.createElement('div');\n"
"        item.className = 'rule-item ' + (idx === currentRuleIdx ? 'active' : '');\n"
"        item.onclick = () => selectRule(idx);\n"
"        item.innerHTML = `\n"
"          <div class=\"rule-header\">\n"
"            <div class=\"rule-name\">${r.name || '未命名规则'}</div>\n"
"            <label class=\"switch\" onclick=\"event.stopPropagation()\">\n"
"              <input type=\"checkbox\" ${r.enabled ? 'checked' : ''} onchange=\"toggleRuleEnabled(${idx}, this.checked)\">\n"
"              <span class=\"slider\"></span>\n"
"            </label>\n"
"          </div>\n"
"          <div style=\"display:flex; gap:0.5rem; align-items:center;\">\n"
"            <span class=\"badge badge-method\">${r.match?.method || 'ANY'}</span>\n"
"            <span class=\"rule-url\">${r.match?.url || '/'}</span>\n"
"          </div>\n"
"        `;\n"
"        list.appendChild(item);\n"
"      });\n"
"    }\n"
"\n"
"    function selectRule(idx) {\n"
"      currentRuleIdx = idx;\n"
"      renderRuleList();\n"
"      const r = rulesData[idx];\n"
"      if (!r) return;\n"
"      document.getElementById('emptyState').style.display = 'none';\n"
"      document.getElementById('editorForm').style.display = 'flex';\n"
"      document.getElementById('ruleName').value = r.name || '';\n"
"      document.getElementById('matchUrl').value = r.match?.url || '';\n"
"      document.getElementById('matchMethod').value = r.match?.method || '';\n"
"      const delay = r.inject?.delay_ms || 0;\n"
"      document.getElementById('delaySlider').value = delay;\n"
"      updateDelayVal(delay);\n"
"      document.getElementById('statusCode').value = r.inject?.status_code || 0;\n"
"      document.getElementById('bodyFind').value = r.inject?.body_modify?.find || '';\n"
"      document.getElementById('bodyReplace').value = r.inject?.body_modify?.replace || '';\n"
"      document.getElementById('closeDrop').checked = r.inject?.action === 'close_immediately';\n"
"    }\n"
"\n"
"    function syncEditorToData() {\n"
"      if (currentRuleIdx < 0 || !rulesData[currentRuleIdx]) return;\n"
"      const r = rulesData[currentRuleIdx];\n"
"      r.name = document.getElementById('ruleName').value;\n"
"      if (!r.match) r.match = {};\n"
"      r.match.url = document.getElementById('matchUrl').value;\n"
"      r.match.method = document.getElementById('matchMethod').value;\n"
"      if (!r.inject) r.inject = {};\n"
"      r.inject.delay_ms = parseInt(document.getElementById('delaySlider').value) || 0;\n"
"      r.inject.status_code = parseInt(document.getElementById('statusCode').value) || 0;\n"
"      const find = document.getElementById('bodyFind').value;\n"
"      const replace = document.getElementById('bodyReplace').value;\n"
"      if (find) {\n"
"        r.inject.body_modify = { find, replace };\n"
"      } else {\n"
"        delete r.inject.body_modify;\n"
"      }\n"
"      if (document.getElementById('closeDrop').checked) {\n"
"        r.inject.action = 'close_immediately';\n"
"      } else {\n"
"        delete r.inject.action;\n"
"      }\n"
"    }\n"
"\n"
"    function updateDelayVal(val) { document.getElementById('delayVal').innerText = val + ' ms'; syncEditorToData(); }\n"
"    ['ruleName','matchUrl','matchMethod','statusCode','bodyFind','bodyReplace','closeDrop'].forEach(id => {\n"
"      const el = document.getElementById(id);\n"
"      if (el) el.oninput = syncEditorToData;\n"
"    });\n"
"\n"
"    function toggleRuleEnabled(idx, checked) {\n"
"      if (rulesData[idx]) rulesData[idx].enabled = checked;\n"
"    }\n"
"\n"
"    function addNewRule() {\n"
"      const newRule = { name: '新故障规则', enabled: true, match: { url: '/api/' }, inject: { delay_ms: 1000 } };\n"
"      rulesData.push(newRule);\n"
"      selectRule(rulesData.length - 1);\n"
"    }\n"
"\n"
"    function deleteCurrentRule() {\n"
"      if (currentRuleIdx >= 0) {\n"
"        rulesData.splice(currentRuleIdx, 1);\n"
"        currentRuleIdx = -1;\n"
"        document.getElementById('editorForm').style.display = 'none';\n"
"        document.getElementById('emptyState').style.display = 'block';\n"
"        renderRuleList();\n"
"      }\n"
"    }\n"
"\n"
"    async function saveRules() {\n"
"      syncEditorToData();\n"
"      try {\n"
"        const res = await fetch('/api/rules', {\n"
"          method: 'POST',\n"
"          headers: { 'Content-Type': 'application/json' },\n"
"          body: JSON.stringify(rulesData, null, 2)\n"
"        });\n"
"        if (res.ok) alert('✅ 规则保存成功，已同步至 rules.json 并实时生效！');\n"
"      } catch(e) { alert('❌ 保存失败: ' + e); }\n"
"    }\n"
"\n"
"    fetchRules();\n"
"    setInterval(fetchMetrics, 3000);\n"
"  </script>\n"
"</body>\n"
"</html>\n";

bool handle_web_ui_request(conn_t *conn) {
    if (!conn) return false;

    /* 1. 检查请求是否为 Web UI HTML 界面 (/ 或 /ui 或 /ui/) */
    if (strcmp(conn->path, "/") == 0 || strcmp(conn->path, "/ui") == 0 || strcmp(conn->path, "/ui/") == 0) {
        size_t body_len = strlen(WEB_UI_HTML);
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                 "HTTP/1.1 200 OK\r\n"
                 "Content-Type: text/html; charset=utf-8\r\n"
                 "Content-Length: %zu\r\n"
                 "Connection: close\r\n\r\n"
                 "%s", body_len, WEB_UI_HTML);
        conn->resp_len = strlen(conn->resp_buf);
        conn->state = CONN_STATE_WRITE_CLIENT;
        log_info("Web UI 界面访问: 成功渲染前端控制台");
        return true;
    }

    /* 2. 检查请求是否为获取规则 JSON API (GET /api/rules) */
    if (strcmp(conn->path, "/api/rules") == 0 && strcasecmp(conn->method, "GET") == 0) {
        FILE *fp = fopen("rules.json", "rb");
        char content[16384] = "[]";
        if (fp) {
            size_t n = fread(content, 1, sizeof(content) - 1, fp);
            content[n] = '\0';
            fclose(fp);
        }
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                 "HTTP/1.1 200 OK\r\n"
                 "Content-Type: application/json; charset=utf-8\r\n"
                 "Content-Length: %zu\r\n"
                 "Connection: close\r\n\r\n"
                 "%s", strlen(content), content);
        conn->resp_len = strlen(conn->resp_buf);
        conn->state = CONN_STATE_WRITE_CLIENT;
        return true;
    }

    /* 3. 检查请求是否为保存规则 JSON API (POST /api/rules) */
    if (strcmp(conn->path, "/api/rules") == 0 && strcasecmp(conn->method, "POST") == 0) {
        char *body = strstr(conn->req_buf, "\r\n\r\n");
        if (body) {
            body += 4; // 跳过 \r\n\r\n
            FILE *fp = fopen("rules.json", "wb");
            if (fp) {
                fwrite(body, 1, strlen(body), fp);
                fclose(fp);
                log_success("Web UI: 用户通过界面保存并更新了 rules.json 配置文件！");
            }
        }
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                 "HTTP/1.1 200 OK\r\n"
                 "Content-Type: application/json\r\n"
                 "Content-Length: 15\r\n"
                 "Connection: close\r\n\r\n"
                 "{\"status\":\"ok\"}");
        conn->resp_len = strlen(conn->resp_buf);
        conn->state = CONN_STATE_WRITE_CLIENT;
        return true;
    }

    /* 4. 检查请求是否为获取运行指标 API (GET /api/metrics) */
    if (strcmp(conn->path, "/api/metrics") == 0) {
        char json_buf[512];
        snprintf(json_buf, sizeof(json_buf),
                 "{\"total\":%llu,\"forwarded\":%llu,\"injected\":%llu,\"delay\":%llu}",
                 (unsigned long long)g_metrics.total_requests,
                 (unsigned long long)g_metrics.forwarded_requests,
                 (unsigned long long)g_metrics.injected_faults,
                 (unsigned long long)g_metrics.delay_injections);
        snprintf(conn->resp_buf, sizeof(conn->resp_buf),
                 "HTTP/1.1 200 OK\r\n"
                 "Content-Type: application/json\r\n"
                 "Content-Length: %zu\r\n"
                 "Connection: close\r\n\r\n"
                 "%s", strlen(json_buf), json_buf);
        conn->resp_len = strlen(conn->resp_buf);
        conn->state = CONN_STATE_WRITE_CLIENT;
        return true;
    }

    return false; // 不是 Web UI 相关的请求，继续后续正常代理流程
}
